# Generated by Django 3.0.8 on 2020-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_library_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='library',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist',
            new_name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='note',
            field=models.CharField(blank=True, max_length=129),
        ),
    ]
