# Generated by Django 3.0.8 on 2020-09-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0007_auto_20200902_1233'),
        ('users', '0008_auto_20200914_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books_1.Book'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books_1.Book'),
        ),
    ]
