# Generated by Django 3.0.8 on 2020-10-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201021_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='note',
        ),
    ]
