# Generated by Django 3.0.8 on 2020-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201031_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='groups',
            field=models.ManyToManyField(default=None, to='users.Group'),
        ),
    ]
