# Generated by Django 3.0.8 on 2020-11-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201031_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupList',
        ),
    ]
