# Generated by Django 3.0.8 on 2020-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0002_auto_20200807_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.TextField(default=None),
        ),
    ]
