# Generated by Django 3.0.8 on 2020-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0004_auto_20200826_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
