# Generated by Django 3.0.8 on 2020-09-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0006_book_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='book',
            name='wishlists',
        ),
    ]
