# Generated by Django 3.0.8 on 2020-10-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0007_auto_20200902_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
