# Generated by Django 3.0.8 on 2020-10-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_1', '0008_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
