# Generated by Django 3.0.8 on 2020-11-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group'),
        ),
    ]
